### ISSUE TITLE
Typescript Migration

### ISSUE THREAD

**Issue by DecliningLotus** [fontsource/google-font-metadata#18]
For future maintainability and quality control, migrating the whole repository to Typescript would be positive step forward.

Something to be addressed in the near future.

**Comment by DecliningLotus** [comment]
Resolved in #23.

**Comment by thealjey** [comment]
@DecliningLotus this is great, but the types are not actually published to npm
so, as a result, this project benefits from typescript, but for any project project that uses this package it remains the same 

Worse in some cases, because typescript checks for json files are a bit more relaxed.
Because now we actually need the types, where as before we were "fine" without them.

**Comment by DecliningLotus** [comment]
@thealjey, appreciate the notice. I will admit, this is my first time using TypeScript from scratch on a project and so I was bound to do some things wrong.

I might be able to look into this in about 10 days since I have huge commitments right now, but if you're happy to assist to any scale, that would be amazing.

**Comment by DecliningLotus** [comment]
Hopefully resolved in #51.
